package com.ded_technologies.functioninjava;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.nio.charset.Charset;
import javax.swing.DefaultBoundedRangeModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author timko
 */
public class GUI extends javax.swing.JFrame {
    /*
    - модель для прогресса
    - кол-во строк
    - кол-во столбцов
    - разделитель
    - модель выпадающего списка
    - окно сохранения файла
    */
    private final DefaultBoundedRangeModel model = new DefaultBoundedRangeModel(0, 0, 0, 100);
    public static int totalRows,
                      totalColumns,
                      separator;
    private final DefaultComboBoxModel<String> columns;
    private final JFileChooser fileChooser = new JFileChooser();
    /**
     * Creates new form GUI
     */
    public GUI() {
        this.columns = new DefaultComboBoxModel<>();
        columns.addElement("");
        columns.addElement("50");
        columns.addElement("100");
        columns.addElement("500");
        FileNameExtensionFilter filter = new FileNameExtensionFilter("CSV-файлы", "csv");
        fileChooser.setFileFilter(filter);
        initComponents();
    }
    /*Метод записи в файл*/
    private void setFile(String str, File file) {
        try (BufferedWriter buff = new BufferedWriter(new OutputStreamWriter(new FileOutputStream(file+".csv", true), Charset.forName("Cp1251")));) {
            buff.write(str);
            buff.flush();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(rootPane, "Ошибка записи файла: " + e.getMessage(), "Ошибка", JOptionPane.ERROR_MESSAGE);
        }
    }
    /*Метод генерации тренда*/
    public void getTrend(File file){
        Thread trend = new Thread(()->{
            int loop = totalRows/10000;//кол-во итераций
            double process;
            CreateFile.setEnabled(false);
            ParseToString pts = new ParseToString();
            pts.getParam();//генерируем параметры потоков
            setFile(pts.getNameColumns(), file);//пишем имена параметров в файл
            setFile(pts.getMeas(), file);//пишем размерности в файл
            for (int i=0; i<loop; i++){
                try {
                    int current_loop=i;
                    Thread array_of_threads = new Thread(()->{
                        try {
                            pts.sendThread(current_loop);//передаем текущую позицию по времени (строке)
                        } catch (InterruptedException e) {
                            JOptionPane.showMessageDialog(rootPane, e.getMessage(), "Ошибка", JOptionPane.ERROR_MESSAGE);
                        }
                    });
                    array_of_threads.start();//выполняет массив потоков
                    array_of_threads.join();//ждем, пока поток текущей итерации закончит вычисления и будет завершен
                    setFile(pts.parse(), file);//получаем строку, готовую для записи в файл и записываем
                    process = ((double)(i+1)/loop)*100;
                    model.setValue((int) process);
                } catch (InterruptedException ex) {
                    JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Ошибка", JOptionPane.ERROR_MESSAGE);
                }
            }
            JOptionPane.showMessageDialog(rootPane, "Тренд '"+file+"' сгенерирован", "Завершение", JOptionPane.INFORMATION_MESSAGE);
            CreateFile.setEnabled(true);
            model.setValue(model.getMinimum());
        });
        trend.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Row1 = new javax.swing.JRadioButton();
        Row2 = new javax.swing.JRadioButton();
        Row3 = new javax.swing.JRadioButton();
        CreateFile = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jSlider1 = new javax.swing.JSlider();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Создание csv-файлов трендов");
        setResizable(false);

        buttonGroup1.add(Row1);
        Row1.setText("10 000");
        Row1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Row1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(Row2);
        Row2.setText("100 000");
        Row2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Row2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(Row3);
        Row3.setText("1 000 000");
        Row3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Row3ActionPerformed(evt);
            }
        });

        CreateFile.setText("Создать файл");
        CreateFile.setEnabled(false);
        CreateFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateFileActionPerformed(evt);
            }
        });

        jLabel1.setText("Количество строк:");

        jLabel2.setText("Количество параметров:");

        jComboBox1.setEditable(true);
        jComboBox1.setMaximumRowCount(4);
        jComboBox1.setModel(columns);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jProgressBar1.setModel(model);
        jProgressBar1.setStringPainted(true);

        jLabel3.setText("Разделитель:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Табуляция", "Точка с запятой" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Разреженные данные:");

        jCheckBox1.setText("ДА");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jSlider1.setMajorTickSpacing(15);
        jSlider1.setMaximum(90);
        jSlider1.setMinimum(10);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        jSlider1.setSnapToTicks(true);
        jSlider1.setValue(10);
        jSlider1.setEnabled(false);
        jSlider1.setVerifyInputWhenFocusTarget(false);

        jLabel5.setText("Степень заполнения:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CreateFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox1)
                                    .addComponent(Row2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Row1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Row3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 40, Short.MAX_VALUE))
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Row1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Row2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Row3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CreateFile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Row3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Row3ActionPerformed
        totalRows = 1000000;
    }//GEN-LAST:event_Row3ActionPerformed

    private void Row1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Row1ActionPerformed
        totalRows = 10000;
    }//GEN-LAST:event_Row1ActionPerformed

    private void Row2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Row2ActionPerformed
        totalRows = 100000;
    }//GEN-LAST:event_Row2ActionPerformed

    private void CreateFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateFileActionPerformed
        /*Сохранение файла*/
        fileChooser.setDialogTitle("Сохранение файла");
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int result = fileChooser.showSaveDialog(rootPane);
        if (result == JFileChooser.APPROVE_OPTION ){
            getTrend(fileChooser.getSelectedFile());
        }
    }//GEN-LAST:event_CreateFileActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        /*Выбор/ввод кол-ва параметров*/
        try{
            totalColumns = Integer.valueOf((String) jComboBox1.getSelectedItem());
        }catch (NumberFormatException e){
            JOptionPane.showMessageDialog(rootPane, e.getMessage(), "Ошибка", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        /*Выбор разделителя*/
        separator = jComboBox2.getSelectedIndex();
        CreateFile.setEnabled(true);
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        jSlider1.setEnabled(true);
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*Поток графического интерфейса*/
        Thread g = new Thread(()->{
            GUI gui = new GUI();
            gui.setVisible(true);
        });
        g.start();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateFile;
    private javax.swing.JRadioButton Row1;
    private javax.swing.JRadioButton Row2;
    private javax.swing.JRadioButton Row3;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    public static javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    public static javax.swing.JSlider jSlider1;
    // End of variables declaration//GEN-END:variables
}
